modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="starhud"
version="${version}"
displayName="StarHUD"
description= "a mod that provides fancy and fresh HUDs"
authors="Finside"
logoFile="icon.png"

[[mixins]]
config = "starhud.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.1)"
ordering="NONE"
side="BOTH"